node {
  name: "IteratorV2"
  op: "IteratorV2"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "output_shapes"
    value {
      list {
        shape {
          dim {
            size: -1
          }
        }
      }
    }
  }
  attr {
    key: "output_types"
    value {
      list {
        type: DT_INT32
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "IteratorGetNext"
  op: "IteratorGetNext"
  input: "IteratorV2"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "output_shapes"
    value {
      list {
        shape {
          dim {
            size: -1
          }
        }
      }
    }
  }
  attr {
    key: "output_types"
    value {
      list {
        type: DT_INT32
      }
    }
  }
}
node {
  name: "_retval_Add_0_0"
  op: "_Retval"
  input: "ngraph_cluster_4"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "index"
    value {
      i: 0
    }
  }
}
node {
  name: "ngraph_cluster_4"
  op: "NGraphEncapsulate"
  input: "IteratorGetNext"
  device: "/job:localhost/replica:0/task:0/device:CPU:0"
  attr {
    key: "Targuments"
    value {
      list {
        type: DT_INT32
      }
    }
  }
  attr {
    key: "Tresults"
    value {
      list {
        type: DT_INT32
      }
    }
  }
  attr {
    key: "ngraph_backend"
    value {
      s: "INTERPRETER"
    }
  }
  attr {
    key: "ngraph_cluster"
    value {
      i: 4
    }
  }
  attr {
    key: "ngraph_device_id"
    value {
      s: ""
    }
  }
  attr {
    key: "ngraph_graph_id"
    value {
      i: 3
    }
  }
}
library {
}
versions {
  producer: 38
  min_consumer: 12
}
