node {
  name: "c1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000\003\000\000\000\004\000\000\000"
      }
    }
  }
}
node {
  name: "c2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\001\000\000\000\002\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "add1"
  op: "Add"
  input: "c1"
  input: "c2"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "c3"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
          dim {
            size: 2
          }
        }
        tensor_content: "\005\000\000\000\000\000\000\000\001\000\000\000\004\000\000\000"
      }
    }
  }
}
node {
  name: "add2"
  op: "Add"
  input: "add1"
  input: "c3"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "add2_retval"
  op: "_Retval"
  input: "add2"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "index"
    value {
      i: 0
    }
  }
}
versions {
  producer: 175
}
