# ==============================================================================
#  Copyright 2019 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ==============================================================================

workspace(name = "ngraph_bridge")
load("@//tf_configure:tf_configure.bzl", "tf_configure")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

tf_configure(
    name = "local_config_tf",
)

http_archive(
    name = "ngraph",
    build_file = "//:bazel/ngraph.BUILD",
    sha256 = "c7fa9f0594294de0834dbb8ef5ad8385de837ce027e08091129c7ca945b7e049",
    strip_prefix = "ngraph-0.18.0-rc.2",
    urls = [
        "https://mirror.bazel.build/github.com/NervanaSystems/ngraph/archive/v0.18.0-rc.2.tar.gz",
        "https://github.com/NervanaSystems/ngraph/archive/v0.18.0-rc.2.tar.gz",
    ],
)

http_archive(
    name = "nlohmann_json_lib",
    build_file = "//:bazel/nlohmann_json.BUILD",
    sha256 = "e0b1fc6cc6ca05706cce99118a87aca5248bd9db3113e703023d23f044995c1d",
    strip_prefix = "json-3.5.0",
    urls = [
        "https://mirror.bazel.build/github.com/nlohmann/json/archive/v3.5.0.tar.gz",
        "https://github.com/nlohmann/json/archive/v3.5.0.tar.gz",
    ],
)
