# ==============================================================================
#  Copyright 2019 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ==============================================================================

workspace(name = "ngraph_bridge")
load("@//tf_configure:tf_configure.bzl", "tf_configure")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

tf_configure(
    name = "local_config_tf",
)

http_archive(
    name = "ngraph",
    build_file = "//:bazel/ngraph.BUILD",
    sha256 = "bc818db68986ad309a6d546fa875cddf94196a51f8c7082631aeffd124859b58",
    strip_prefix = "ngraph-0.23.0-rc.3",
    urls = [
        "https://mirror.bazel.build/github.com/NervanaSystems/ngraph/archive/v0.23.0-rc.3.tar.gz",
        "https://github.com/NervanaSystems/ngraph/archive/v0.23.0-rc.3.tar.gz"
    ],
)

http_archive(
    name = "nlohmann_json_lib",
    build_file = "//:bazel/nlohmann_json.BUILD",
    sha256 = "e0b1fc6cc6ca05706cce99118a87aca5248bd9db3113e703023d23f044995c1d",
    strip_prefix = "json-3.5.0",
    urls = [
        "https://mirror.bazel.build/github.com/nlohmann/json/archive/v3.5.0.tar.gz",
        "https://github.com/nlohmann/json/archive/v3.5.0.tar.gz",
    ],
)

http_archive(
        name = "tbb",
        build_file = "//:bazel/tbb.BUILD",
        sha256 = "c3245012296f09f1418b78a8c2f17df5188b3bd0db620f7fd5fabe363320805a",
        strip_prefix = "tbb-2019_U1",
        urls = [
            "http://mirror.tensorflow.org/github.com/01org/tbb/archive/2019_U1.zip",
            "https://github.com/01org/tbb/archive/2019_U1.zip",
        ],
    )

http_archive(
        name = "eigen",
        build_file = "//:bazel/eigen.BUILD",
        sha256 = "74845ea27e19a1bcf63f3f271de62e06798f23e0467bb9d45b83a94918941b23",
        strip_prefix = "eigen-eigen-20cbc6576426",
        urls = [
            "http://mirror.tensorflow.org/bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
            "https://bitbucket.org/eigen/eigen/get/20cbc6576426.tar.gz",
        ],
    )

http_archive(
        name = "mkl_dnn",
        build_file = "//:bazel/mkl_dnn.BUILD",
        sha256 = "38a1c02104ee9f630c1ad68164119cd58ad0aaf59e04ccbe7bd5781add7bfbea",
        strip_prefix = "mkl-dnn-0.18",
        urls = [
            "http://mirror.tensorflow.org/github.com/intel/mkl-dnn/archive/v0.18.tar.gz",
            "https://github.com/intel/mkl-dnn/archive/v0.18.tar.gz",
        ],
    )

http_archive(
        name = "mkl_linux",
        build_file = "//:bazel/mkl.BUILD",
        sha256 = "f4129843d5c2996419f96f10928edd02b2150998861a088dc7cfa1b6a058102a",
        strip_prefix = "mklml_lnx_2019.0.3.20190220",
        urls = [
            "http://mirror.tensorflow.org/github.com/intel/mkl-dnn/releases/download/v0.18/mklml_lnx_2019.0.3.20190220.tgz",
            "https://github.com/intel/mkl-dnn/releases/download/v0.18/mklml_lnx_2019.0.3.20190220.tgz",
        ],
    )
