# ==============================================================================
#  Copyright 2019 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ==============================================================================

workspace(name = "ngraph_bridge")
load("//tf_configure:tf_configure.bzl", "tf_configure")

tf_configure(
    name = "local_config_tf",
)

new_http_archive(
    name = "ngraph",
    build_file = "bazel/ngraph.BUILD",
    sha256 = "741812c14c70882e1ddb28e27c4a5e890b5fef3b2ec81ab6662dcd47127e9a35",
    strip_prefix = "ngraph-d3453447883fe48e63126316d5da72fcbd47dded",
    urls = [
        "https://mirror.bazel.build/github.com/NervanaSystems/ngraph/archive/d3453447883fe48e63126316d5da72fcbd47dded.zip",
        "https://github.com/NervanaSystems/ngraph/archive/d3453447883fe48e63126316d5da72fcbd47dded.zip",
    ],
)

new_http_archive(
    name = "nlohmann_json_lib",
    build_file = "bazel/nlohmann_json.BUILD",
    sha256 = "e0b1fc6cc6ca05706cce99118a87aca5248bd9db3113e703023d23f044995c1d",
    strip_prefix = "json-3.5.0",
    urls = [
        "https://mirror.bazel.build/github.com/nlohmann/json/archive/v3.5.0.tar.gz",
        "https://github.com/nlohmann/json/archive/v3.5.0.tar.gz",
    ],
)
