# ==============================================================================
#  Copyright 2019-2020 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ==============================================================================

# Environment to build and unit-test ngraph-tensorflow-bridge

# Environment to build and unit-test ngraph on debian (stretch)
# with gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
# with python 3.5.3

FROM debian:stretch

RUN apt-get update && apt-get install -y \
    python3-dev python3-pip \ 
    virtualenv \
    git \
    unzip wget \
    sudo \
    zlib1g zlib1g-dev bash-completion \
    build-essential cmake \
    libtinfo-dev \
    zip golang-go \
    locate curl \
    libssl-dev libbz2-dev libsqlite3-dev
    
# Report which gcc and g++ versions are present
RUN which gcc && gcc --version || true
RUN which c++ && c++ --version || true
RUN python3 --version || true
RUN python --version || true

# The "locate" command uses a prepopulated index.  If this index is not built,
# then "locate" will find absolutely nothing.  In Tensorflow's configure,
# this manifests itself as a silent failure of the configure script to run to
# completion.  Therefore, updatedb MUST BE RUN to provide an index for "locate".
RUN updatedb

# The pip-upgrade for pip, setuptools, and virtualenv is to avoid a nasty
#   bug in setuptools: "_NamespacePath object has no attribute sort"
RUN pip3 install --upgrade pip setuptools virtualenv==16.1.0

# We include pytest so the Docker image can be used for daily validation
RUN pip3 install --upgrade pytest

# We include openjdk-8-jdk
RUN apt-get update && apt-get install -y openjdk-8-jdk

# This bazel version 21 works with current TF
ARG BAZEL_VERSION=0.25.2
RUN wget --no-verbose -c https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb
RUN dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb || true

# Copy in the run-as-user.sh script
# This will allow the builds, which are done in a mounted directory, to
# be run as the user who runs "docker run".  This then allows the mounted
# directory to be properly deleted by the user later (e.g. by jenkins).
WORKDIR /home

